controller_list:
  - name: /thormang3/right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - r_arm_sh_p1
      - r_arm_sh_r
      - r_arm_sh_p2
      - r_arm_el_y
      - r_arm_wr_r
      - r_arm_wr_y
      - r_arm_wr_p
  # - name: left_arm_controller
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   default: true
  #   joints:
  #     - l_arm_sh_p1
  #     - l_arm_sh_r
  #     - l_arm_sh_p2
  #     - l_arm_el_y
  #     - l_arm_wr_r
  #     - l_arm_wr_y
  #     - l_arm_wr_p
  # - name: right_arm_with_torso_controller
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   default: true
  #   joints:
  #     - torso_y
  #     - r_arm_sh_p1
  #     - r_arm_sh_r
  #     - r_arm_sh_p2
  #     - r_arm_el_y
  #     - r_arm_wr_r
  #     - r_arm_wr_y
  #     - r_arm_wr_p
  # - name: left_arm_with_torso_controller
  #   action_ns: follow_joint_trajectory
  #   type: FollowJointTrajectory
  #   default: true
  #   joints:
  #     - torso_y
  #     - l_arm_sh_p1
  #     - l_arm_sh_r
  #     - l_arm_sh_p2
  #     - l_arm_el_y
  #     - l_arm_wr_r
  #     - l_arm_wr_y
  #     - l_arm_wr_p
  # - name: right_hand_controller
  #   action_ns: gripper_action
  #   type: GripperCommand
  #   default: true
  #   parallel: true
  #   joints:
  #     - r_arm_grip
  #     - r_arm_grip_1
  # - name: left_hand_controller
  #   action_ns: gripper_action
  #   type: GripperCommand
  #   default: true
  #   parallel: true
  #   joints:
  #     - l_arm_grip
  #     - l_arm_grip_1